# Created by trellis-cli v1.14.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  trellis-spinupwp.com:
    site_hosts:
      - canonical: www.trellis-spinupwp.com
        redirects:
          - trellis-spinupwp.com
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: false
